name: Compile test

on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "master" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Check out my other private repo
          uses: actions/checkout@master
          with:
            repository: UnspaghettifyKart/action-build-private-file
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Install dependencies
          run: |
            sudo apt-get install -y binutils-mips python3 libaudiofile

        - name: Build
          run: |
            make -C tools
            make