name: Macos Compile test

on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Complementary file
        uses: actions/checkout@v4
        with:
          path: complementary_file
          repository: UnspaghettifyKart/action-build-private-file
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          brew update
          brew install python3 capstone coreutils make pkg-config tehzz/n64-dev/mips64-elf-binutils
      - name: Build
        run: |
          cp -r complementary_file/* .
          make
