name: Windows Compile test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Complementary file
        uses: actions/checkout@v4
        with:
          path: complementary_file
          repository: UnspaghettifyKart/action-build-private-file
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          Invoke-WebRequest https://github.com/coco875/mk64-tools/releases/download/v0.0.6/mips-tools-chain-windows.zip -OutFile mips-tools-chain-windows.zip
          Expand-Archive mips-tools-chain-windows.zip -DestinationPath mips-tools-chain-windows
          Copy-Item -Path mips-tools-chain-windows/mingw64 -Destination tools -Recurse
      - name: Build
        run: |
          cp -r complementary_file/* .
          make